### ISSUE TITLE
Seconds per year is not correct

### ISSUE THREAD

**Issue by geesen** [mike182uk/timestring#34]
The result for a year, e.g. of 

`console.log(timestring("1y"));`

is 29030400

but a year has 31,536,000 seconds.

This is also wrong in the tests!
I think, it comes from the wrong calculation, which uses "monthsPerYear * weeksPerMonth" and weeksPerMonth is 4. 

Is this intended, or would it be better to use e.g. an additonal "daysPerYear" option?

**Comment by mike182uk** [comment]
Hey @geesen,

Sorry for the really late reply to this.

Yep your right, the calculation doesn't produce the correct result due to the fact the number of days per month fluctuate.

Adding a `daysPerYear` option seems to be the most sensible approach so i have gone ahead and implemented this in `timestring@5.0.0`. I've set this value to `365.25` by default, but this can be configured for more precision if required.

Thanks for the bug report and the suggestion!
