### ISSUE TITLE
Seconds per month is not correct

### ISSUE THREAD

**Issue by Andiedie** [mike182uk/timestring#35]
By default:
1. There are 7 days per week
2. There are 4 weeks per month

So there are 28 days per month.

**Seconds per month = 28 * 24 * 60 * 60 = 2419200**

However
```js
const timestring = require('timestring');

let time = timestring('1mon');
console.log(time);
// print 2629800
```

and `2629800` is `30.4375` days.

**Comment by mike182uk** [comment]
Hey @Andiedie 

I recently made a change around what is happening here, see https://github.com/mike182uk/timestring/issues/34

Seeming though the number of days in a month can vary, what was previously being calculated was not entirely accurate - well its accurate based on the defaults, but possibly not expected behaviour. 

I updated the documentation to indicate that converting months and years to seconds is calculated based on the `daysPerYear` config option and not the other options. Maybe i should re-word how the config is used to avoid confusion?

If you prefer the old behaviour, you could set `daysPerYear` to `336`

**Comment by Andiedie** [comment]
Thanks for help.
